dist: xenial
language: clojure
lein: 2.9.1
jdk: openjdk11
install:
  - ./chrome.sh
  - ./sassc.sh
before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./prepare.sh
  - ./restart.sh
script: java -jar test/target/test.jar