---
version: '2.2'
services:

  db:
    image: postgres:11-alpine
    container_name: db
    ports:
      - "25432:25432"
    environment:
      POSTGRES_PASSWORD: aAbB24CcO03XxZuUiiiX2
    command: -p 25432
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    container_name: zk
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
    ports:
      - "22181:2181"
    mem_limit: 200m
    restart: always


  kafka:
    image: confluentinc/cp-kafka:5.2.1
    container_name: kafka
    ports:
      - "19092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
    mem_limit: 1300m
    restart: always

  schema-registry:
    image: confluentinc/cp-schema-registry:5.2.1
    container_name: sr
    ports:
      - "18081:8081"
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:18081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:22181
    mem_limit: 400m
    restart: always
